-- Generated by Oracle SQL Developer Data Modeler 4.0.1.836
--   at:        2014-07-21 11:52:58 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE TEST_agreement CASCADE CONSTRAINTS ;

DROP TABLE TEST_department CASCADE CONSTRAINTS ;

DROP TABLE TEST_vendor CASCADE CONSTRAINTS ;

CREATE TABLE TEST_agreement
  (
    agreement_id       INTEGER NOT NULL ,
    TEST_department_id INTEGER ,
    TEST_vendor_id     INTEGER
  ) ;
ALTER TABLE TEST_agreement ADD CONSTRAINT TEST_agreement_PK PRIMARY KEY ( agreement_id ) ;

CREATE TABLE TEST_department
  (
    department_id INTEGER NOT NULL ,
    name          VARCHAR2 (250)
  ) ;
ALTER TABLE TEST_department ADD CONSTRAINT TEST_department_PK PRIMARY KEY ( department_id ) ;

CREATE TABLE TEST_vendor
  (
    vendor_id INTEGER NOT NULL ,
    name      VARCHAR2 (255)
  ) ;
ALTER TABLE TEST_vendor ADD CONSTRAINT TEST_vendor_PK PRIMARY KEY ( vendor_id ) ;

ALTER TABLE TEST_agreement ADD CONSTRAINT TEST_agreement_department_FK FOREIGN KEY ( TEST_department_id ) REFERENCES TEST_department ( department_id ) ;

ALTER TABLE TEST_agreement ADD CONSTRAINT TEST_agreement_vendor_FK FOREIGN KEY ( TEST_vendor_id ) REFERENCES TEST_vendor ( vendor_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
